name: aks_internal
description: Shared utilities for Flutter apps.
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  jiffy: ^6.3.2
  l: ^5.0.0
  mobx: ^2.5.0
  octo_image: ^2.1.0
  parse_server_sdk_flutter: ^9.0.0
  shimmer: ^3.0.0
  very_good_infinite_list: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^8.0.0
